#bundle install after installing gems, or changing the gemfile

source "https://rubygems.org"
gem "rspec"
gem "sinatra"
gem "rack"
gem "rack-test"
gem "sinatra-contrib" 
gem "guard"
gem "guard-rspec"


