#Guardfile

guard :rspec, cmd: 'bundle exec rspec --color' do  #integrating with rspec #bundle exec rspec is a safeguard
	
	watch(%r{^spec/.+_spec\.rb$})  #anything inside rspec folder, using reg expressions to include all of that instead of listing
	watch(%r{^lib/(.+)\.rb$}) { |m| "spec/#{m;[1]}_spec.rb"}
	watch("app.rb") { |m| "spec/app_spec.rb"}
end

